disabled_rules: # rule identifiers to exclude from running
 # - closing_brace 
 # - colon         
 # - comma         
 # - conditional_binding_cascade 
 # - control_statement           
 # - custom_rules                
 # - cyclomatic_complexity       
 # - empty_count                 
 # - file_length                 
 # - force_cast                  
 # - force_try                   
 # - force_unwrapping            
 # - function_body_length        
 # - function_parameter_count    
 # - leading_whitespace          
 # - legacy_constant             
 # - legacy_constructor          
 # - line_length                 
 - missing_docs                
 # - nesting                     
 # - opening_brace 
 # - operator_whitespace         
 # - return_arrow_whitespace     
 # - statement_position          
 # - todo                        
 # - trailing_newline            
 # - trailing_semicolon          
 - trailing_whitespace         
 # - type_body_length            
 # - type_name                   
 - valid_docs                  
 # - variable_name                
opt_in_rules: # some rules are only opt-in
  -  empty_count
  -  missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  -  VietHearts
excluded: # paths to ignore during linting. Takes precedence over `included`.
  -  Carthage
  -  Pods
  # -  Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  warning: 240
  error: 250
# they can set both implicitly with an array
function_body_length:
  warning: 90
  error: 100
# or they can set both explicitly
file_length:
  warning: 500
  error: 600
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
# variable_name:
#   min_length: # only min_length
#     error: 4 # only error
#   excluded: # excluded via string array
#     -  id
#     -  URL
#     -  GlobalAPIKey
# 
# 
#  Using Swiftlint with command terminal 
#  swiftlint lint --config CalendarView.swiftlint.yml
#  Clear log command + K